[phases.setup]
aptPkgs = ["ffmpeg", "python3", "ca-certificates", "curl"]

[phases.build]
cmds = [
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp",
  "chmod a+rx ./yt-dlp",
  "./yt-dlp --version"
]